#!/usr/bin/env python3
"""Tests for derive-grok.py: a -grok twin is its parent plus the mechanical
transformations and NOTHING else. Includes the GROK_DRIFT negative control
(tamper a twin, the gate must fail). No Codex watchdog/control-guard clone."""
import copy
import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import yaml

SETUP = Path(__file__).resolve().parent.parent
ARCHON = SETUP.parent
GEN = SETUP / "derive-grok.py"

_spec = importlib.util.spec_from_file_location("derive_grok", GEN)
assert _spec is not None and _spec.loader is not None
dg = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(dg)

_cspec = importlib.util.spec_from_file_location("derive_codex", SETUP / "derive-codex.py")
assert _cspec is not None and _cspec.loader is not None
dc = importlib.util.module_from_spec(_cspec)
_cspec.loader.exec_module(dc)

MAIN_TARGETS = ["full-sdlc-api", "bugfix", "full-sdlc-web", "full-sdlc-api-lite", "bugfix-lite"]


def load(p):
    return yaml.safe_load(Path(p).read_text(encoding="utf-8"))


def walk(nodes):
    for n in nodes:
        yield n
        if isinstance(n.get("loop_group"), dict):
            yield from walk(n["loop_group"].get("nodes") or [])


class TwinShape(unittest.TestCase):
    def check(self, target):
        parent = load(ARCHON / "workflows" / f"{target}.yaml")
        twin_path = ARCHON / "workflows" / f"{target}-grok.yaml"
        self.assertTrue(twin_path.is_file(), f"{twin_path} not generated")
        twin = load(twin_path)
        self.assertEqual(twin["name"], parent["name"] + "-grok")
        self.assertEqual(twin["provider"], "grok")
        self.assertTrue(twin["description"].startswith(parent["description"]))
        self.assertIn("GENERATED by setup/derive-grok.py", twin["description"])
        pn = list(walk(parent["nodes"]))
        tn = list(walk(twin["nodes"]))
        self.assertEqual([n["id"] for n in pn], [n["id"] for n in tn], "node id order drifted")
        # Parents may already carry a Claude no-op `codex-control-guard` node.
        # Keep those bytes. Do not inject Codex's one-time file consumer.
        if "codex-control-guard" not in [n["id"] for n in pn]:
            self.assertNotIn("codex-control-guard", [n["id"] for n in tn])
        for p, t in zip(pn, tn):
            nid = p["id"]
            if p.get("model") == "sonnet":
                self.assertEqual(t.get("model"), dg.DEFAULT_MODEL, f"{nid}: sonnet not remapped")
            elif p.get("model") == "opus":
                self.assertEqual(t.get("model"), dg.FLAGSHIP_MODEL, f"{nid}: opus not remapped")
            else:
                self.assertEqual(p.get("model"), t.get("model"), f"{nid}: model drifted")
            self.assertNotIn("provider", t, f"{nid}: unexpected per-node provider")
            self.assertNotIn("maxBudgetUsd", t, f"{nid}: inert Grok cap survived")
            if p.get("skills"):
                self.assertNotIn("skills", t, f"{nid}: unsupported Grok skills key survived")
                for skill in p["skills"]:
                    self.assertIn(f"/{skill}", t.get("prompt", ""), f"{nid}: Grok slash invocation missing")
                    self.assertNotIn(f"${skill}", t.get("prompt", ""), f"{nid}: Codex $skill token leaked")
            if "prompt" in p:
                if p.get("skills"):
                    self.assertTrue(t["prompt"].endswith(p["prompt"]), f"{nid}: parent prompt was not preserved")
                else:
                    self.assertEqual(t.get("prompt"), p["prompt"], f"{nid}: prompt drifted")
            for k in set(p) | set(t):
                if k in ("model", "bash", "loop_group", "maxBudgetUsd", "skills", "prompt"):
                    continue
                self.assertEqual(p.get(k), t.get(k), f"{nid}: field {k} drifted")
            if "bash" in p:
                expected_bash, guard_count = dg.swap_billing_guard(p["bash"])
                self.assertEqual(t.get("bash"), expected_bash, f"{nid}: bash transform drifted")
                if guard_count:
                    self.assertNotIn("ANTHROPIC_API_KEY", t["bash"], f"{nid}: claude guard survived")
                    self.assertIn("BILLING_GUARD=FAIL", t["bash"], f"{nid}: grok guard missing")
                    self.assertIn("XAI_API_KEY", t["bash"])
                    self.assertIn("GROK_CODE_XAI_API_KEY", t["bash"])
                    self.assertIn('GROK_AUTH="${GROK_HOME:-$HOME/.grok}/auth.json"', t["bash"])
                    self.assertNotIn(".agents/skills", t["bash"], f"{nid}: Codex .agents mirror leaked")
                    self.assertNotIn("ARCHON_CODEX_LITE_GUARD_FILE", t["bash"])
                    self.assertNotIn("CONTROL_TOKEN_FROM_LAST_LAUNCH", t["bash"])
                    self.assertNotIn("codex-lite-one-time-guard", t["bash"])

    def test_all_main_targets(self):
        for t in MAIN_TARGETS:
            with self.subTest(target=t):
                self.check(t)


class TransformStats(unittest.TestCase):
    def test_guard_counts_and_no_codex_machinery(self):
        for t in MAIN_TARGETS:
            _, text, stats = dg.derive(t)
            self.assertEqual(stats["guard_swaps"], 1, f"{t}: guard_swaps={stats['guard_swaps']}")
            self.assertGreater(stats["caps_stripped"], 0, f"{t}: no Grok caps stripped")
            self.assertNotIn("ARCHON_CODEX_LITE_GUARD_FILE", text)
            self.assertNotIn("codex-lite-one-time-guard", text)
            self.assertNotIn(".agents/skills", text)
            self.assertNotIn("CONTROL_TOKEN_FROM_LAST_LAUNCH", text)

    def test_inherited_control_guard_stays_parent_noop(self):
        for t in ("bugfix", "bugfix-lite", "full-sdlc-web", "full-sdlc-api-lite"):
            parent = load(ARCHON / "workflows" / f"{t}.yaml")
            twin = load(ARCHON / "workflows" / f"{t}-grok.yaml")
            p = next(n for n in walk(parent["nodes"]) if n["id"] == "codex-control-guard")
            g = next(n for n in walk(twin["nodes"]) if n["id"] == "codex-control-guard")
            self.assertEqual(g.get("bash"), p.get("bash"), t)
            self.assertIn("CODEX_CONTROL_GUARD=PASS provider=claude", g["bash"])
            self.assertNotIn("os.unlink", g["bash"])

    def test_wraps_have_no_guard(self):
        for t in ["wrap-review", "wrap-docreview", "wrap-fixer", "wrap-implement"]:
            _, _, stats = dg.derive(t)
            self.assertEqual(stats["guard_swaps"], 0, t)

    def test_production_target_rejects_missing_billing_transform(self):
        parent = copy.deepcopy(load(ARCHON / "workflows" / "bugfix-lite.yaml"))
        preflight = next(n for n in walk(parent["nodes"]) if n["id"] == "preflight")
        preflight["bash"], removed = dg.GUARD_RE.subn("", preflight["bash"], count=1)
        self.assertEqual(removed, 1, "fixture parent no longer has a billing guard")

        with mock.patch.object(dg, "load_yaml", return_value=parent), \
             self.assertRaisesRegex(dg.GrokError, "expected one billing guard"):
            dg.derive("bugfix-lite")

    def test_production_target_rejects_duplicated_billing_transform(self):
        parent = copy.deepcopy(load(ARCHON / "workflows" / "bugfix-lite.yaml"))
        preflight = next(n for n in walk(parent["nodes"]) if n["id"] == "preflight")
        matched = dg.GUARD_RE.search(preflight["bash"])
        self.assertIsNotNone(matched)
        preflight["bash"] += "\n" + matched.group(0)
        with mock.patch.object(dg, "load_yaml", return_value=parent), \
             self.assertRaisesRegex(dg.GrokError, "expected one billing guard"):
            dg.derive("bugfix-lite")


class CapabilityLint(unittest.TestCase):
    def test_capability_lint_rejects_unsupported_fields(self):
        for field in sorted(dg.UNSUPPORTED_GROK_FIELDS):
            with self.subTest(field=field):
                with self.assertRaises(dg.GrokError):
                    dg.enforce_capabilities({"id": "x", field: True}, "fixture")

    def test_thinking_is_kept(self):
        node = {"id": "x", "thinking": "high"}
        stripped = dg.enforce_capabilities(node, "fixture")
        self.assertEqual(stripped, 0)
        self.assertEqual(node.get("thinking"), "high")

    def test_max_budget_is_stripped(self):
        node = {"id": "x", "maxBudgetUsd": 3}
        stripped = dg.enforce_capabilities(node, "fixture")
        self.assertEqual(stripped, 1)
        self.assertNotIn("maxBudgetUsd", node)

    def test_parent_billing_regex_matches_codex_derive(self):
        self.assertEqual(dg.GUARD_RE.pattern, dc.GUARD_RE.pattern)


class BillingAuth(unittest.TestCase):
    def test_oidc_nested_auth_passes(self):
        ok, line = dg.eval_grok_auth({
            "https://auth.x.ai::<id>": {
                "auth_mode": "oidc",
                "refresh_token": "rt",
                "key": "session-key",
            }
        })
        self.assertTrue(ok)
        self.assertEqual(line, "BILLING_GUARD=OK oidc")

    def test_flat_oidc_auth_passes(self):
        ok, line = dg.eval_grok_auth({
            "auth_mode": "oidc", "refresh_token": "rt", "key": "session-key",
        })
        self.assertTrue(ok)
        self.assertEqual(line, "BILLING_GUARD=OK oidc")

    def test_api_key_mode_fails(self):
        ok, line = dg.eval_grok_auth({"auth_mode": "api_key", "key": "sk"})
        self.assertFalse(ok)
        self.assertIn("auth_mode='api_key'", line)
        self.assertNotIn("sk", line)

    def test_missing_tokens_fail(self):
        ok, line = dg.eval_grok_auth({"auth_mode": "oidc"})
        self.assertFalse(ok)
        self.assertIn("tokens missing", line)

    def test_empty_object_fails(self):
        ok, line = dg.eval_grok_auth({})
        self.assertFalse(ok)
        self.assertIn("no account records", line)


class DriftGate(unittest.TestCase):
    def run_gen(self, args):
        return subprocess.run([sys.executable, str(GEN), *args], capture_output=True, encoding="utf-8")

    def test_check_mode_clean(self):
        r = self.run_gen(["--all", "--check"])
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertEqual(r.stdout.count("GROK_DRIFT=OK"), len(dg.TARGETS))

    def test_tampered_twin_fails_check(self):
        with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as fh:
            shipped = (ARCHON / "workflows" / "bugfix-lite-grok.yaml").read_text(encoding="utf-8")
            fh.write(shipped.replace("PREFLIGHT=FAIL", "PREFLIGHT=FAIL # edited", 1))
            tmp = fh.name
        r = self.run_gen(["bugfix-lite", "--out", tmp, "--check"])
        self.assertEqual(r.returncode, 1, r.stdout + r.stderr)
        self.assertIn("GROK_DRIFT=FAIL bugfix-lite-grok", r.stdout)

    def test_missing_twin_fails_check(self):
        r = self.run_gen(["bugfix-lite", "--out", "/nonexistent/x.yaml", "--check"])
        self.assertNotEqual(r.returncode, 0)
        self.assertIn("DERIVE_GROK=FAIL", r.stdout + r.stderr)


class GuardTextProperties(unittest.TestCase):
    def test_grok_guard_is_fail_closed_bash(self):
        twin = load(ARCHON / "workflows" / "full-sdlc-api-grok.yaml")
        pre = next(n for n in twin["nodes"] if n["id"] == "preflight")
        self.assertIn("\nPY_BILLING\n", pre["bash"], "heredoc terminator indented or missing")
        r = subprocess.run(["bash", "-n"], input=pre["bash"], capture_output=True, encoding="utf-8")
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_generated_python_accepts_oidc_fixture(self):
        twin = load(ARCHON / "workflows" / "bugfix-lite-grok.yaml")
        pre = next(n for n in twin["nodes"] if n["id"] == "preflight")
        start = pre["bash"].index("import json, sys")
        end = pre["bash"].index("\nPY_BILLING\n")
        py = pre["bash"][start:end]
        with tempfile.TemporaryDirectory() as td:
            auth = Path(td) / "auth.json"
            auth.write_text(json.dumps({
                "https://auth.x.ai::fixture": {
                    "auth_mode": "oidc",
                    "refresh_token": "rt",
                    "key": "session-key",
                }
            }), encoding="utf-8")
            r = subprocess.run(
                [sys.executable, "-", str(auth)],
                input=py, capture_output=True, encoding="utf-8",
            )
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertIn("BILLING_GUARD=OK oidc", r.stdout)

    def test_generated_python_rejects_unreadable(self):
        twin = load(ARCHON / "workflows" / "bugfix-lite-grok.yaml")
        pre = next(n for n in twin["nodes"] if n["id"] == "preflight")
        start = pre["bash"].index("import json, sys")
        end = pre["bash"].index("\nPY_BILLING\n")
        py = pre["bash"][start:end]
        r = subprocess.run(
            [sys.executable, "-", "/nonexistent/auth.json"],
            input=py, capture_output=True, encoding="utf-8",
        )
        self.assertEqual(r.returncode, 1)
        self.assertIn("BILLING_GUARD=FAIL grok auth unreadable", r.stdout)

    def test_api_key_env_fails_closed(self):
        twin = load(ARCHON / "workflows" / "bugfix-lite-grok.yaml")
        pre = next(n for n in twin["nodes"] if n["id"] == "preflight")
        snippet = """
set -euo pipefail
for v in XAI_API_KEY GROK_CODE_XAI_API_KEY; do
  test -z "$(printenv "$v")" || { echo "BILLING_GUARD=FAIL $v is set - would bill API, not subscription"; exit 1; }
done
echo BILLING_GUARD=OK
"""
        self.assertIn("XAI_API_KEY GROK_CODE_XAI_API_KEY", pre["bash"])
        env = dict(os.environ, XAI_API_KEY="sk-test")
        r = subprocess.run(["bash", "-c", snippet], capture_output=True, encoding="utf-8", env=env)
        self.assertEqual(r.returncode, 1)
        self.assertIn("BILLING_GUARD=FAIL XAI_API_KEY is set", r.stdout)


if __name__ == "__main__":
    unittest.main()
