#!/usr/bin/env python3
"""Tests for derive-codex.py: a -codex twin is its parent plus the six
mechanical transformations and NOTHING else. Includes the CODEX_DRIFT
negative control (tamper a twin, the gate must fail)."""
import copy
import importlib.util
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import yaml

SETUP = Path(__file__).resolve().parent.parent
ARCHON = SETUP.parent
GEN = SETUP / "derive-codex.py"

_spec = importlib.util.spec_from_file_location("derive_codex", GEN)
assert _spec is not None and _spec.loader is not None
dc = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(dc)

MAIN_TARGETS = ["full-sdlc-api", "bugfix", "full-sdlc-web", "full-sdlc-api-lite", "bugfix-lite"]


def load(p):
    return yaml.safe_load(Path(p).read_text(encoding="utf-8"))


def walk(nodes):
    for n in nodes:
        yield n
        if isinstance(n.get("loop_group"), dict):
            yield from walk(n["loop_group"].get("nodes") or [])


class TwinShape(unittest.TestCase):
    def check(self, target):
        parent = load(ARCHON / "workflows" / f"{target}.yaml")
        twin_path = ARCHON / "workflows" / f"{target}-codex.yaml"
        self.assertTrue(twin_path.is_file(), f"{twin_path} not generated")
        twin = load(twin_path)
        self.assertEqual(twin["name"], parent["name"] + "-codex")
        self.assertEqual(twin["provider"], "codex")
        self.assertTrue(twin["description"].startswith(parent["description"]))
        self.assertIn("GENERATED by setup/derive-codex.py", twin["description"])
        pn = list(walk(parent["nodes"]))
        tn = list(walk(twin["nodes"]))
        self.assertEqual([n["id"] for n in pn], [n["id"] for n in tn], "node id order drifted")
        for p, t in zip(pn, tn):
            nid = p["id"]
            # model rules
            if p.get("model") == "sonnet":
                self.assertNotIn("model", t, f"{nid}: sonnet not stripped")
            elif p.get("model") == "opus":
                self.assertEqual(t.get("model"), dc.FLAGSHIP_MODEL, f"{nid}: opus not remapped")
            else:
                self.assertEqual(p.get("model"), t.get("model"), f"{nid}: model drifted")
            # per-node provider never appears in the codex-native default
            self.assertNotIn("provider", t, f"{nid}: unexpected per-node provider")
            # every field except model/bash byte-identical
            for k in set(p) | set(t):
                if k in ("model", "bash", "loop_group"):
                    continue
                self.assertEqual(p.get(k), t.get(k), f"{nid}: field {k} drifted")
            # bash: identical unless the parent bash carried the guard or SK asserts
            if "bash" in p:
                if p["bash"] == t.get("bash"):
                    continue
                self.assertNotIn("ANTHROPIC_API_KEY", t["bash"], f"{nid}: claude guard survived")
                self.assertIn("BILLING_GUARD=FAIL", t["bash"], f"{nid}: codex guard missing")
                if 'test -f "$SK/ce-code-review/SKILL.md"' in p["bash"]:
                    self.assertIn('$ASK/ce-code-review/SKILL.md', t["bash"], f"{nid}: .agents mirror missing")
                if 'test -f "$SK/ce-doc-review/SKILL.md"' in p["bash"]:
                    self.assertIn('$ASK/ce-doc-review/SKILL.md', t["bash"], f"{nid}: .agents doc mirror missing")

    def test_all_main_targets(self):
        for t in MAIN_TARGETS:
            with self.subTest(target=t):
                self.check(t)


class TransformStats(unittest.TestCase):
    def test_guard_and_mirror_counts(self):
        for t in MAIN_TARGETS:
            _, _, stats = dc.derive(t)
            self.assertEqual(stats["guard_swaps"], 1, f"{t}: guard_swaps={stats['guard_swaps']}")
            self.assertEqual(stats["agents_inserts"], 1, f"{t}: agents_inserts={stats['agents_inserts']}")

    def test_wraps_have_no_guard(self):
        for t in ["wrap-review", "wrap-docreview", "wrap-fixer", "wrap-implement"]:
            _, _, stats = dc.derive(t)
            self.assertEqual(stats["guard_swaps"], 0, t)


class PinReviewClaude(unittest.TestCase):
    def test_hybrid_pins_skills_nodes(self):
        _, text, _ = dc.derive("bugfix", pin_review_claude=True)
        twin = yaml.safe_load(text)
        pinned = [n for n in walk(twin["nodes"]) if n.get("skills")]
        self.assertTrue(pinned, "no skills nodes found")
        for n in pinned:
            self.assertEqual(n.get("provider"), "claude", f"{n['id']}: not pinned")
            self.assertEqual(n.get("model"), "sonnet", f"{n['id']}: pinned node lost its model")

    def test_default_is_codex_native(self):
        _, text, _ = dc.derive("bugfix")
        twin = yaml.safe_load(text)
        for n in walk(twin["nodes"]):
            if n.get("skills"):
                self.assertNotIn("provider", n, f"{n['id']}: pinned without the flag")
                self.assertNotIn("model", n, f"{n['id']}: sonnet not stripped on skills node")


class DriftGate(unittest.TestCase):
    def run_gen(self, args):
        return subprocess.run([sys.executable, str(GEN), *args], capture_output=True, encoding="utf-8")

    def test_check_mode_clean(self):
        r = self.run_gen(["--all", "--check"])
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertEqual(r.stdout.count("CODEX_DRIFT=OK"), len(dc.TARGETS))

    def test_tampered_twin_fails_check(self):
        # negative control: a hand edit must trip the gate
        with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as fh:
            shipped = (ARCHON / "workflows" / "bugfix-lite-codex.yaml").read_text(encoding="utf-8")
            fh.write(shipped.replace("PREFLIGHT=FAIL", "PREFLIGHT=FAIL # edited", 1))
            tmp = fh.name
        r = self.run_gen(["bugfix-lite", "--out", tmp, "--check"])
        self.assertEqual(r.returncode, 1, r.stdout + r.stderr)
        self.assertIn("CODEX_DRIFT=FAIL bugfix-lite-codex", r.stdout)

    def test_missing_twin_fails_check(self):
        r = self.run_gen(["bugfix-lite", "--out", "/nonexistent/x.yaml", "--check"])
        self.assertNotEqual(r.returncode, 0)
        self.assertIn("DERIVE_CODEX=FAIL", r.stdout + r.stderr)


class GuardTextProperties(unittest.TestCase):
    def test_codex_guard_is_fail_closed_bash(self):
        # the heredoc terminator must sit at column 0 of the bash body (a
        # non-<<- heredoc never matches an indented terminator)
        twin = load(ARCHON / "workflows" / "full-sdlc-api-codex.yaml")
        pre = next(n for n in twin["nodes"] if n["id"] == "preflight")
        self.assertIn("\nPY_BILLING\n", pre["bash"], "heredoc terminator indented or missing")
        r = subprocess.run(["bash", "-n"], input=pre["bash"], capture_output=True, encoding="utf-8")
        self.assertEqual(r.returncode, 0, r.stderr)


if __name__ == "__main__":
    unittest.main()
