#!/usr/bin/env python3
"""Generate a `-grok` twin of an Archon workflow (provider: grok).

Usage: derive-grok.py <target> [--out <path>] [--check]
       derive-grok.py --all [--check]

  <target>   one of TARGETS below (the parent YAML in workflows/)
  --out      write the YAML here instead of workflows/<name>-grok.yaml
  --check    do not write; exit 1 if the shipped twin differs from the
             regeneration (package.sh's GROK_DRIFT step)
  --all      run every target

The twin is DEFINED by the parent plus these mechanical transformations and
NOTHING else (every other node byte is the parent's):
  1. name        -> <name>-grok; description gets a generated-twin marker
  2. provider    -> grok (parent must declare provider: claude)
  3. model       -> `model: sonnet` and `model: opus` become DEFAULT_MODEL /
                    FLAGSHIP_MODEL (both grok-4.6 today; Grok CLI has no cheaper
                    worker SKU)
  4. billing guard -> the ANTHROPIC_*/CLAUDE_* subscription guard block in the
                    preflight bash is replaced by an xAI OIDC guard on the
                    effective GROK_HOME's auth.json (fail-closed, typed
                    BILLING_GUARD=FAIL). API-key env vars fail closed.
  5. `skills:` nodes become explicit `/skill-name` slash invocations (Grok's
                    native skill syntax, not Codex `$skill-name`) and the
                    unsupported YAML `skills:` key is removed
  6. unsupported cost caps are removed; other Claude-only fields fail
                    derivation. `thinking` is kept (Grok CLI has
                    --reasoning-effort).

Vanilla coleam00/Archon has no `provider: grok` yet (built-ins are claude/codex;
community is pi/opencode/copilot). These YAMLs are generate+drift until an
upstream community provider lands. Do not target a fork.

This is the Codex twin's mechanical sibling, not a second control surface:
no Codex `.agents` mirror, no one-time `codex-control-guard`, no
archon-run.py watchdog rewrite.

Hand-editing a generated twin is forbidden; package.sh regenerates and diffs
(GROK_DRIFT=FAIL on any divergence).
"""
import argparse
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ARCHON = os.path.dirname(HERE)

_spec = importlib.util.spec_from_file_location("derive_lite", os.path.join(HERE, "derive-lite.py"))
assert _spec is not None and _spec.loader is not None
_dl = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_dl)
dump_yaml, load_yaml = _dl.dump_yaml, _dl.load_yaml

TARGETS = [
    "full-sdlc-api",
    "bugfix",
    "full-sdlc-web",
    "full-sdlc-api-lite",
    "bugfix-lite",
    "wrap-review",
    "wrap-docreview",
    "wrap-fixer",
    "wrap-implement",
]

# Grok CLI 1.0.34 default is grok-4.6 (grok-4.5 is the only other listed SKU).
# There is no cheaper worker model, so sonnet and opus both pin explicitly.
DEFAULT_MODEL = "grok-4.6"
FLAGSHIP_MODEL = "grok-4.6"
PRODUCTION_TARGETS = {
    "full-sdlc-api", "bugfix", "full-sdlc-web", "full-sdlc-api-lite", "bugfix-lite",
}

# Claude-only fields a Grok CLI node cannot honor until a vanilla provider
# maps them. thinking is kept: Grok has --reasoning-effort. sandbox is kept:
# Grok has --sandbox profiles. Cost caps are stripped, not failed.
UNSUPPORTED_GROK_FIELDS = {
    "hooks", "agents", "fallbackModel", "systemPrompt", "betas", "settingSources",
}

MARKER = (
    " [grok twin - GENERATED by setup/derive-grok.py from {parent}.yaml;"
    " never hand-edit; regenerate: python3 setup/derive-grok.py {target}]"
)


class GrokError(SystemExit):
    def __init__(self, msg):
        super().__init__(f"DERIVE_GROK=FAIL {msg}")


# Same parent-block matcher as derive-codex.GUARD_RE. Tests pin the two equal.
GUARD_RE = re.compile(
    r"(?:[ \t]*# Billing guard: runs MUST bill the Claude subscription[^\n]*\n"
    r"[ \t]*# Any of these outranks[^\n]*\n)?"
    r"([ \t]*)for v in ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN CLAUDE_API_KEY CLAUDE_CODE_OAUTH_TOKEN ANTHROPIC_PROFILE; do\n"
    r"[^\n]*\n"
    r"[ \t]*done\n"
    r"[ \t]*grep -q 'apiKeyHelper'[^\n]*\n"
)

GROK_GUARD = """\
# Billing guard (grok): runs MUST bill the xAI subscription (auth_mode "oidc"
# in the effective GROK_HOME), never an API key. Fail closed when an API-key
# env var is set, or when the auth file is missing, unreadable, not OIDC, or
# token-less.
for v in XAI_API_KEY GROK_CODE_XAI_API_KEY; do
  test -z "$(printenv "$v")" || { echo "BILLING_GUARD=FAIL $v is set - would bill API, not subscription"; exit 1; }
done
GROK_AUTH="${GROK_HOME:-$HOME/.grok}/auth.json"
python3 - "$GROK_AUTH" <<'PY_BILLING' || exit 1
import json, sys
p = sys.argv[1]
try:
    d = json.load(open(p))
except Exception as e:
    print(f"BILLING_GUARD=FAIL grok auth unreadable at {p}: {e}"); sys.exit(1)
records = []
if isinstance(d, dict) and isinstance(d.get("auth_mode"), str):
    records.append(d)
elif isinstance(d, dict):
    records = [v for v in d.values() if isinstance(v, dict) and "auth_mode" in v]
if not records:
    print(f"BILLING_GUARD=FAIL grok auth has no account records at {p} - run: grok login"); sys.exit(1)
ok = False
for rec in records:
    mode = rec.get("auth_mode")
    if mode != "oidc":
        print(f"BILLING_GUARD=FAIL grok auth_mode={mode!r} at {p} - would not bill the xAI subscription"); sys.exit(1)
    if rec.get("refresh_token") and rec.get("key"):
        ok = True
if not ok:
    print(f"BILLING_GUARD=FAIL grok tokens missing at {p} - run: grok login"); sys.exit(1)
print("BILLING_GUARD=OK oidc")
PY_BILLING
if [ -n "${GROK_HOME:-}" ] && [ "$GROK_AUTH" != "$HOME/.grok/auth.json" ] && cmp -s "$GROK_AUTH" "$HOME/.grok/auth.json" 2>/dev/null; then
  echo "BILLING_GUARD=WARN grok auth is a byte-copy of ~/.grok/auth.json (shared refresh pair) - prefer a dedicated login"
fi
"""


def eval_grok_auth(data):
    """Return (ok, typed_line) for a parsed auth.json. Never includes token values."""
    records = []
    if isinstance(data, dict) and isinstance(data.get("auth_mode"), str):
        records.append(data)
    elif isinstance(data, dict):
        records = [v for v in data.values() if isinstance(v, dict) and "auth_mode" in v]
    if not records:
        return False, "BILLING_GUARD=FAIL grok auth has no account records"
    for rec in records:
        mode = rec.get("auth_mode")
        if mode != "oidc":
            return False, (
                f"BILLING_GUARD=FAIL grok auth_mode={mode!r} - would not bill the xAI subscription"
            )
        if not (rec.get("refresh_token") and rec.get("key")):
            return False, "BILLING_GUARD=FAIL grok tokens missing"
    return True, "BILLING_GUARD=OK oidc"


def swap_billing_guard(bash):
    """Replace the Claude-subscription guard with the grok OIDC guard.
    Returns (new_bash, n_replaced). The heredoc terminator stays at column 0."""
    def repl(m):
        indent = m.group(1)
        out = []
        for line in GROK_GUARD.rstrip("\n").split("\n"):
            if line == "PY_BILLING":
                out.append(line + "\n")
            else:
                out.append(indent + line + "\n")
        return "".join(out)
    return GUARD_RE.subn(repl, bash)


def walk_nodes(nodes):
    for n in nodes:
        yield n
        if isinstance(n.get("loop_group"), dict):
            yield from walk_nodes(n["loop_group"].get("nodes") or [])


def make_skills_explicit(node, target):
    """Translate unsupported YAML `skills:` into Grok slash-command invocations."""
    skills = node.get("skills") or []
    if not skills:
        return 0
    prompt = node.get("prompt")
    if not isinstance(prompt, str):
        raise GrokError(f"{target}/{node.get('id')}: skills require an inline prompt for Grok translation")
    tokens = [f"/{name}" for name in skills]
    for token in tokens:
        if token in prompt:
            raise GrokError(f"{target}/{node.get('id')}: parent prompt already carries {token}; remove duplicate translation")
    node["prompt"] = (
        f"Invoke {' and '.join(tokens)} as Grok slash-commands for this node.\n\n{prompt}"
    )
    del node["skills"]
    return 1


def enforce_capabilities(node, target):
    bad = sorted(UNSUPPORTED_GROK_FIELDS.intersection(node))
    if bad:
        raise GrokError(f"{target}/{node.get('id')}: unsupported Grok fields: {', '.join(bad)}")
    stripped = 1 if "maxBudgetUsd" in node else 0
    node.pop("maxBudgetUsd", None)
    return stripped


def derive(target):
    if target not in TARGETS:
        raise GrokError(f"unknown target {target} (valid: {', '.join(TARGETS)})")
    parent_path = os.path.join(ARCHON, "workflows", f"{target}.yaml")
    if not os.path.isfile(parent_path):
        raise GrokError(f"parent missing: {parent_path}")
    doc = load_yaml(parent_path)
    if doc.get("provider") != "claude":
        raise GrokError(f"{target}: parent provider is {doc.get('provider')!r}, expected 'claude'")

    name = doc["name"] + "-grok"
    out = {"name": name,
           "description": doc.get("description", "") + MARKER.format(parent=target, target=target)}
    for k, v in doc.items():
        if k in ("name", "description", "provider", "nodes"):
            continue
        out[k] = v
    out["provider"] = "grok"
    out["nodes"] = doc["nodes"]

    guard_swaps = 0
    skill_rewrites = 0
    caps_stripped = 0
    for node in walk_nodes(out["nodes"]):
        if node.get("skills"):
            skill_rewrites += make_skills_explicit(node, target)
        caps_stripped += enforce_capabilities(node, target)
        m = node.get("model")
        if m == "sonnet":
            node["model"] = DEFAULT_MODEL
        elif m == "opus":
            node["model"] = FLAGSHIP_MODEL
        elif m is not None:
            raise GrokError(f"{target}/{node.get('id')}: unexpected model {m!r} (rules cover sonnet/opus only)")
        if isinstance(node.get("bash"), str):
            node["bash"], n = swap_billing_guard(node["bash"])
            guard_swaps += n

    if target in PRODUCTION_TARGETS and guard_swaps != 1:
        raise GrokError(f"{target}: expected one billing guard, got {guard_swaps}")
    return name, dump_yaml(out), {
        "guard_swaps": guard_swaps,
        "skill_rewrites": skill_rewrites,
        "caps_stripped": caps_stripped,
    }


def run_one(target, out_path, check):
    name, text, stats = derive(target)
    tgt = out_path or os.path.join(ARCHON, "workflows", f"{name}.yaml")
    if check:
        if not os.path.isfile(tgt):
            raise GrokError(f"shipped twin missing: {tgt}")
        with open(tgt, encoding="utf-8") as fh:
            if fh.read() != text:
                print(f"GROK_DRIFT=FAIL {name} (regenerate: python3 setup/derive-grok.py {target})")
                sys.exit(1)
        print(f"GROK_DRIFT=OK {name}")
        return
    with open(tgt, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"DERIVE_GROK=OK {name} guard_swaps={stats['guard_swaps']} skill_rewrites={stats['skill_rewrites']} caps_stripped={stats['caps_stripped']} -> {os.path.relpath(tgt, ARCHON)}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("target", nargs="?", choices=TARGETS)
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--out")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    if not a.all and not a.target:
        ap.error("a target or --all is required")
    if a.all and a.out:
        ap.error("--out is single-target only")
    for t in (TARGETS if a.all else [a.target]):
        run_one(t, a.out, a.check)


if __name__ == "__main__":
    main()
