#!/usr/bin/env python3
"""Generate a `-codex` twin of an Archon workflow (provider: codex).

Usage: derive-codex.py <target> [--out <path>] [--check] [--pin-review-claude]
       derive-codex.py --all [--check]

  <target>   one of TARGETS below (the parent YAML in workflows/)
  --out      write the YAML here instead of workflows/<name>-codex.yaml
  --check    do not write; exit 1 if the shipped twin differs from the
             regeneration (package.sh's CODEX_DRIFT step)
  --all      run every target
  --pin-review-claude
             hybrid mode: pin every `skills:` node to provider: claude
             (fallback if the CE skills do not work under codex; S0-4
             proved they DO, so the shipped default is codex-native)

The twin is DEFINED by the parent plus these mechanical transformations and
NOTHING else (every other node byte is the parent's):
  1. name        -> <name>-codex; description gets a generated-twin marker
  2. provider    -> codex (parent must declare provider: claude)
  3. model       -> `model: sonnet` stripped (falls through to
                    assistants.codex.model, default gpt-5.6-sol, observed on
                    the S0-1 probe); `model: opus` becomes an explicit
                    FLAGSHIP_MODEL
  4. billing guard -> the ANTHROPIC_*/CLAUDE_* subscription guard block in the
                    preflight bash is replaced by a ChatGPT-auth guard on the
                    effective CODEX_HOME's auth.json (fail-closed, typed
                    BILLING_GUARD=FAIL)
  5. staged-skill preflight -> the `$SK/ce-*/SKILL.md` assertions gain mirror
                    assertions on <root>/.agents/skills (codex's discovery
                    dir, staged by stage-skills.sh)
  6. `skills:` nodes become explicit `$skill-name` prompt invocations and the
                    unsupported YAML key is removed; with --pin-review-claude
                    they are pinned to provider: claude and KEEP the key/model
  7. unsupported Codex cost caps are removed; any other unsupported provider
                    field fails derivation instead of degrading at runtime
  8. guarded twins replace `codex-control-guard`'s Claude no-op with a mandatory
                    guarded-launch assertion that runs on every resume

Hand-editing a generated twin is forbidden; package.sh regenerates and diffs
(CODEX_DRIFT=FAIL on any divergence). Textual diffability never outranks the
provider capability contract: a Codex twin carries no inert safety field.
"""
import argparse
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ARCHON = os.path.dirname(HERE)

_spec = importlib.util.spec_from_file_location("derive_lite", os.path.join(HERE, "derive-lite.py"))
assert _spec is not None and _spec.loader is not None
_dl = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_dl)
dump_yaml, load_yaml = _dl.dump_yaml, _dl.load_yaml

TARGETS = [
    "full-sdlc-api",
    "bugfix",
    "full-sdlc-web",
    "full-sdlc-api-lite",
    "bugfix-lite",
    "wrap-review",
    "wrap-docreview",
    "wrap-fixer",
    "wrap-implement",
]

# Explicit flagship for the parents' `model: opus` critic nodes. The codex
# default (assistants.codex.model) resolved to gpt-5.6-sol on the S0-1 probe;
# pinning it here keeps the critic nodes' intent ("strongest model") explicit
# and stable if the adapter default ever drifts.
FLAGSHIP_MODEL = "gpt-5.6-sol"
LITE_TARGETS = {"full-sdlc-api-lite", "bugfix-lite"}
INJECTED_GUARD_TARGETS = {"full-sdlc-api"}
GUARDED_TARGETS = LITE_TARGETS | {"bugfix", "full-sdlc-api", "full-sdlc-web"}
CONTROL_SCRIPT = "/Users/eduardopicazo/Documents/Workspace/Goodword/.archon/setup/archon-run.py"
UNSUPPORTED_CODEX_FIELDS = {
    "allowed_tools", "denied_tools", "hooks", "agents", "thinking",
    "fallbackModel", "systemPrompt", "betas", "sandbox", "settingSources",
}

MARKER = (
    " [codex twin - GENERATED by setup/derive-codex.py from {parent}.yaml;"
    " never hand-edit; regenerate: python3 setup/derive-codex.py {target}]"
)


class CodexError(SystemExit):
    def __init__(self, msg):
        super().__init__(f"DERIVE_CODEX=FAIL {msg}")


# --------------------------------------------------------- billing guard swap
# The parent guard: optional 2-line comment + the ANTHROPIC_* for-loop + the
# apiKeyHelper line. Matched against the DEDENTED bash body yaml.safe_load
# produces (block indentation is stripped; inner lines keep their own offsets).
GUARD_RE = re.compile(
    r"(?:[ \t]*# Billing guard: runs MUST bill the Claude subscription[^\n]*\n"
    r"[ \t]*# Any of these outranks[^\n]*\n)?"
    r"([ \t]*)for v in ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN CLAUDE_API_KEY CLAUDE_CODE_OAUTH_TOKEN ANTHROPIC_PROFILE; do\n"
    r"[^\n]*\n"
    r"[ \t]*done\n"
    r"[ \t]*grep -q 'apiKeyHelper'[^\n]*\n"
)

CODEX_GUARD = """\
# Billing guard (codex): runs MUST bill the ChatGPT plan (auth_mode "chatgpt"
# in the effective CODEX_HOME), never an API key. Fail closed when the auth
# file is missing, unreadable, keyed to the API, or token-less.
CODEX_AUTH="${CODEX_HOME:-$HOME/.codex}/auth.json"
python3 - "$CODEX_AUTH" <<'PY_BILLING' || exit 1
import json, sys
p = sys.argv[1]
try:
    d = json.load(open(p))
except Exception as e:
    print(f"BILLING_GUARD=FAIL codex auth unreadable at {p}: {e}"); sys.exit(1)
if d.get("auth_mode") != "chatgpt":
    print(f"BILLING_GUARD=FAIL codex auth_mode={d.get('auth_mode')!r} at {p} - would not bill the ChatGPT plan"); sys.exit(1)
t = d.get("tokens") or {}
if not (t.get("access_token") and t.get("refresh_token")):
    print(f"BILLING_GUARD=FAIL codex tokens missing at {p} - run: CODEX_HOME=<home> codex login"); sys.exit(1)
print("BILLING_GUARD=OK chatgpt")
PY_BILLING
# WARN (not FAIL) when the dedicated home's auth is a byte-copy of the personal
# ~/.codex login: the two homes then share ONE refresh-token pair, and either
# side's refresh can strand the other. A real `CODEX_HOME=<home> codex login`
# is the durable setup (install skill §6).
if [ "$CODEX_AUTH" != "$HOME/.codex/auth.json" ] && cmp -s "$CODEX_AUTH" "$HOME/.codex/auth.json" 2>/dev/null; then
  echo "BILLING_GUARD=WARN codex auth is a byte-copy of ~/.codex/auth.json (shared refresh pair) - prefer a dedicated login"
fi
"""


def swap_billing_guard(bash):
    """Replace the Claude-subscription guard with the codex ChatGPT guard.
    Returns (new_bash, n_replaced)."""
    def repl(m):
        indent = m.group(1)
        return "".join(indent + line + "\n" for line in CODEX_GUARD.rstrip("\n").split("\n"))
    return GUARD_RE.subn(repl, bash)


# ------------------------------------------------ staged-skill preflight mirror
# Mirror ONLY what the parent asserts: full-sdlc-api(+lite) assert both skills;
# bugfix(+lite) and full-sdlc-web assert ce-code-review alone.
SK_DOC_ASSERT_RE = re.compile(
    r'([ \t]*)test -f "\$SK/ce-doc-review/SKILL\.md"[^\n]*\n'
)
SK_CODE_ASSERT_RE = re.compile(
    r'([ \t]*)test -f "\$SK/ce-code-review/SKILL\.md"[^\n]*\n'
)

AGENTS_ASSERT_BOTH = """\
# Codex twins: codex discovers skills from <root>/.agents/skills (staged by
# stage-skills.sh next to the .claude links asserted above).
ASK="${SK%/.claude/skills}/.agents/skills"
test -f "$ASK/ce-code-review/SKILL.md" || { echo "PREFLIGHT=FAIL codex-staged ce-code-review missing (run setup/stage-skills.sh)"; exit 1; }
test -f "$ASK/ce-doc-review/SKILL.md"  || { echo "PREFLIGHT=FAIL codex-staged ce-doc-review missing (run setup/stage-skills.sh)"; exit 1; }
"""

AGENTS_ASSERT_CODE = """\
# Codex twins: codex discovers skills from <root>/.agents/skills (staged by
# stage-skills.sh next to the .claude link asserted above).
ASK="${SK%/.claude/skills}/.agents/skills"
test -f "$ASK/ce-code-review/SKILL.md" || { echo "PREFLIGHT=FAIL codex-staged ce-code-review missing (run setup/stage-skills.sh)"; exit 1; }
"""

CODEX_CONTROL_GUARD = """\
set -euo pipefail
python3 - "${ARCHON_CODEX_LITE_GUARD_FILE:-}" <<'PY_CONTROL' || exit 1
import os, pathlib, pwd, re, stat, sys
p = sys.argv[1]
try:
    path = pathlib.Path(p)
    expected_dir = pathlib.Path(pwd.getpwuid(os.getuid()).pw_dir) / ".archon" / "control" / "codex-lite"
    if path.parent.resolve() != expected_dir.resolve():
        raise RuntimeError("guard is outside the fixed private control directory")
    match = re.fullmatch(r"guard-([0-9a-f]{64})", path.name)
    if not match:
        raise RuntimeError("guard filename is not a launcher nonce")
    s = os.lstat(p)
    if not stat.S_ISREG(s.st_mode) or s.st_uid != os.getuid() or s.st_mode & 0o077:
        raise RuntimeError("guard must be an owned mode-0600 regular file")
    with open(p, encoding="utf-8") as fh:
        if fh.read() != f"codex-lite-one-time-guard:{match.group(1)}\\n":
            raise RuntimeError("guard nonce content mismatch")
    os.unlink(p)
except Exception as e:
    print("CODEX_CONTROL_GUARD=FAIL use the guarded archon-run.py surface: " + str(e))
    raise SystemExit(1)
print("CODEX_CONTROL_GUARD=PASS provider=codex one_time=consumed")
PY_CONTROL
"""


def _insert_after(block_text):
    def repl(m):
        indent = m.group(1)
        block = "".join(indent + line + "\n" for line in block_text.rstrip("\n").split("\n"))
        return m.group(0) + block
    return repl


def add_agents_asserts(bash):
    """Mirror the parent's staged-skill assertions onto .agents/skills.
    Returns (new_bash, n_inserted)."""
    new, n = SK_DOC_ASSERT_RE.subn(_insert_after(AGENTS_ASSERT_BOTH), bash)
    if n:
        return new, n
    return SK_CODE_ASSERT_RE.subn(_insert_after(AGENTS_ASSERT_CODE), bash)


# -------------------------------------------------------------------- derive
def walk_nodes(nodes):
    for n in nodes:
        yield n
        if isinstance(n.get("loop_group"), dict):
            yield from walk_nodes(n["loop_group"].get("nodes") or [])


def make_skills_explicit(node, target):
    """Translate unsupported Codex `skills:` into explicit prompt tokens."""
    skills = node.get("skills") or []
    if not skills:
        return 0
    prompt = node.get("prompt")
    if not isinstance(prompt, str):
        raise CodexError(f"{target}/{node.get('id')}: skills require an inline prompt for Codex translation")
    tokens = [f"${name}" for name in skills]
    for token in tokens:
        if token in prompt:
            raise CodexError(f"{target}/{node.get('id')}: parent prompt already carries {token}; remove duplicate translation")
    node["prompt"] = f"Use {' and '.join(tokens)} explicitly for this node.\n\n{prompt}"
    del node["skills"]
    return 1


def enforce_capabilities(node, target):
    bad = sorted(UNSUPPORTED_CODEX_FIELDS.intersection(node))
    context = node.get("context")
    if isinstance(context, dict) and "resume" in context:
        bad.append("context.resume")
    if bad:
        raise CodexError(f"{target}/{node.get('id')}: unsupported Codex fields: {', '.join(bad)}")
    stripped = 1 if "maxBudgetUsd" in node else 0
    node.pop("maxBudgetUsd", None)
    return stripped


def rewrite_lite_controls(obj):
    """Point every rendered approval/control command at the guarded surface."""
    replacements = {
        "DISABLE_OMC=1 archon workflow approve <id> </dev/null >/tmp/archon-approve.log 2>&1 &":
            f"python3 {CONTROL_SCRIPT} approve <id> --token CONTROL_TOKEN_FROM_LAST_LAUNCH",
        'DISABLE_OMC=1 archon workflow reject <id> "why you are stopping it"':
            f'python3 {CONTROL_SCRIPT} reject <id> "why you are stopping it" --token CONTROL_TOKEN_FROM_LAST_LAUNCH',
        "DISABLE_OMC=1 archon workflow abandon <id>":
            f"python3 {CONTROL_SCRIPT} abandon <id> --token CONTROL_TOKEN_FROM_LAST_LAUNCH",
        "DISABLE_OMC=1 archon workflow resume <id>":
            f"python3 {CONTROL_SCRIPT} resume <id> --token CONTROL_TOKEN_FROM_LAST_LAUNCH",
        "archon workflow resume <id>":
            f"python3 {CONTROL_SCRIPT} resume <id> --token CONTROL_TOKEN_FROM_LAST_LAUNCH",
        'for v in approve reject abandon; do':
            'for v in approve reject abandon resume; do',
        'grep -qF "archon workflow $v"':
            'grep -qF "archon-run.py $v"',
    }
    if isinstance(obj, str):
        count = 0
        for old, new in replacements.items():
            n = obj.count(old)
            obj = obj.replace(old, new)
            count += n
        return obj, count
    if isinstance(obj, list):
        out, count = [], 0
        for value in obj:
            value, n = rewrite_lite_controls(value)
            out.append(value); count += n
        return out, count
    if isinstance(obj, dict):
        out, count = {}, 0
        for key, value in obj.items():
            value, n = rewrite_lite_controls(value)
            out[key] = value; count += n
        return out, count
    return obj, 0


def derive(target, pin_review_claude=False):
    if target not in TARGETS:
        raise CodexError(f"unknown target {target} (valid: {', '.join(TARGETS)})")
    parent_path = os.path.join(ARCHON, "workflows", f"{target}.yaml")
    if not os.path.isfile(parent_path):
        raise CodexError(f"parent missing: {parent_path}")
    doc = load_yaml(parent_path)
    if doc.get("provider") != "claude":
        raise CodexError(f"{target}: parent provider is {doc.get('provider')!r}, expected 'claude'")

    name = doc["name"] + "-codex"
    out = {"name": name,
           "description": doc.get("description", "") + MARKER.format(parent=target, target=target)}
    for k, v in doc.items():
        if k in ("name", "description", "provider", "nodes"):
            continue
        out[k] = v
    out["provider"] = "codex"
    out["nodes"] = doc["nodes"]
    if target in INJECTED_GUARD_TARGETS:
        guard_node = {
            "id": "codex-control-guard",
            "always_run": True,
            "timeout": 60000,
            "bash": "echo \"CODEX_CONTROL_GUARD=PASS provider=claude\"\n",
        }
        out["nodes"] = [guard_node, *out["nodes"]]
        if out["nodes"][1].get("id") == "preflight":
            out["nodes"][1]["depends_on"] = ["codex-control-guard"]

    guard_swaps = 0
    agents_inserts = 0
    skill_rewrites = 0
    caps_stripped = 0
    control_guards = 0
    control_rewrites = 0
    for node in walk_nodes(out["nodes"]):
        # 6. skills nodes: hybrid pin BEFORE the model rules so a pinned
        # claude node keeps its parent model.
        pinned = False
        if pin_review_claude and node.get("skills"):
            node["provider"] = "claude"
            pinned = True
        elif node.get("skills"):
            skill_rewrites += make_skills_explicit(node, target)
        if not pinned:
            caps_stripped += enforce_capabilities(node, target)
        # 3. model remap
        if not pinned:
            m = node.get("model")
            if m == "sonnet":
                del node["model"]
            elif m == "opus":
                node["model"] = FLAGSHIP_MODEL
            elif m is not None:
                raise CodexError(f"{target}/{node.get('id')}: unexpected model {m!r} (rules cover sonnet/opus only)")
        # 4+5. bash transforms
        if isinstance(node.get("bash"), str):
            if target in GUARDED_TARGETS and node.get("id") == "codex-control-guard":
                node["bash"] = CODEX_CONTROL_GUARD
                control_guards += 1
            node["bash"], n = swap_billing_guard(node["bash"])
            guard_swaps += n
            node["bash"], n = add_agents_asserts(node["bash"])
            agents_inserts += n

    if target in GUARDED_TARGETS:
        out, control_rewrites = rewrite_lite_controls(out)
        for node in walk_nodes(out["nodes"]):
            approval = node.get("approval")
            if isinstance(approval, dict) and isinstance(approval.get("message"), str):
                approval["message"] += (
                    f" Codex control requirement: use python3 {CONTROL_SCRIPT} for approve, reject, "
                    "abandon, and resume with the token printed by the previous STARTED line; "
                    "raw archon control is rejected by the one-time always-run guard."
                )

    if target in GUARDED_TARGETS and control_guards != 1:
        raise CodexError(f"{target}: expected exactly one codex-control-guard, got {control_guards}")
    return name, dump_yaml(out), {
        "guard_swaps": guard_swaps,
        "agents_inserts": agents_inserts,
        "skill_rewrites": skill_rewrites,
        "caps_stripped": caps_stripped,
        "control_guards": control_guards,
        "control_rewrites": control_rewrites,
    }


def run_one(target, out_path, check, pin):
    name, text, stats = derive(target, pin_review_claude=pin)
    tgt = out_path or os.path.join(ARCHON, "workflows", f"{name}.yaml")
    if check:
        if not os.path.isfile(tgt):
            raise CodexError(f"shipped twin missing: {tgt}")
        with open(tgt, encoding="utf-8") as fh:
            if fh.read() != text:
                print(f"CODEX_DRIFT=FAIL {name} (regenerate: python3 setup/derive-codex.py {target})")
                sys.exit(1)
        print(f"CODEX_DRIFT=OK {name}")
        return
    with open(tgt, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"DERIVE_CODEX=OK {name} guard_swaps={stats['guard_swaps']} agents_inserts={stats['agents_inserts']} skill_rewrites={stats['skill_rewrites']} caps_stripped={stats['caps_stripped']} control_guards={stats['control_guards']} control_rewrites={stats['control_rewrites']} -> {os.path.relpath(tgt, ARCHON)}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("target", nargs="?", choices=TARGETS)
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--out")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--pin-review-claude", action="store_true")
    a = ap.parse_args()
    if not a.all and not a.target:
        ap.error("a target or --all is required")
    if a.all and a.out:
        ap.error("--out is single-target only")
    for t in (TARGETS if a.all else [a.target]):
        run_one(t, a.out, a.check, a.pin_review_claude)


if __name__ == "__main__":
    main()
